#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "Andrea Fioraldi"
description: "My personal web page"
language: "en"

url: http://localhost:4000
url: https://andreafioraldi.github.io/
baseurl: ''

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 2
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
disqus-id: andreafioraldi

enable-share: true
twitter: andreafioraldi
github: andreafioraldi
linkedin: andrea-fioraldi
rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
gems: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/
